bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Alexander Smith
  description: Somatic pipeline for Qiagen Qiaseq assays run in SEGLH NHS labs
  force: true
  is_nfcore: true
  name: seglhqiaseq
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0dev
update: null
#https://github.com/nf-core/modules.git:
#    nf-core:
#      star/align: 'e937c7950af70930d1f34bb961403d9d2aa81c7'
